### PR TITLE
Update dependencies and separate configs to their own files

### PR DESCRIPTION
**Pull request by surilindur**
Here is a set of changes to:
* Move the Jest configs to their own file
* Update to Husky version 9, and updating the hook configurations and gitignore
* Removing coveralls as unnecessary, because coverage is collected by Jest and the reporting is done through the GitHub Actions version of coveralls
* Bumping `@rubensworks/eslint-config` to version 3 and fixing the linter errors that popped up
* Simplifications to `tsconfig.json` includes and excludes
* Relocating `index.ts` to `lib/`
* Updating the Actions workflow versions to latest ones to get rid of the deprecation warnings

Any feedback would be welcome! I will make a separate PR to use the new fragmenter version when it gets released.

### CODE REVIEW

**Comment by rubensworks** [comment]
Just had a look, and everything looks good.
Since the fragmenter has been released as well, feel free to make the new PR :-)

**Comment by surilindur** [comment]
This is now finally ready for review! :snail:

**Comment by rubensworks** [comment]
Thanks!

Is a release for this needed already? (I guess major) Or are more changes planned?

**Comment by surilindur** [comment]
Besides the work on multiple interfaces, I do not have any plans at the moment.

Looking at the commit history, I *think* the only breaking changes are around the (default) CSS version used for serving the content. Is it something that would require a major version bump? The other changes seem to be just a bugfix from Jitse, the various dependency updates and clean-up, but there are no changes to the SolidBench things themselves. Relocating `index.ts` to `lib/` should not break anything, since the `package.json` path for it was also updated, and I doubt anyone directly imports it by path (I hope).

**Pull request merged**
